"""for update

Revision ID: 16e4e7f46abe
Revises: d85b3c80e0
Create Date: 2015-12-04 04:04:55.174750

"""

# revision identifiers, used by Alembic.
revision = '16e4e7f46abe'
down_revision = 'd85b3c80e0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
