"""testtesttest

Revision ID: 30b30b2eff8f
Revises: dd90263b3ea
Create Date: 2015-12-08 23:45:25.405533

"""

# revision identifiers, used by Alembic.
revision = '30b30b2eff8f'
down_revision = 'dd90263b3ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
