"""user

Revision ID: 52d54f94a30a
Revises: 16e4e7f46abe
Create Date: 2015-12-04 04:07:10.538079

"""

# revision identifiers, used by Alembic.
revision = '52d54f94a30a'
down_revision = '16e4e7f46abe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
