"""utf-8

Revision ID: d85b3c80e0
Revises: 34030fb6bded
Create Date: 2015-12-04 03:44:44.432911

"""

# revision identifiers, used by Alembic.
revision = 'd85b3c80e0'
down_revision = '34030fb6bded'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
