k""update

Revision ID: dd90263b3ea
Revises: 52d54f94a30a
Create Date: 2015-12-04 13:26:44.776042

"""

# revision identifiers, used by Alembic.
revision = 'dd90263b3ea'
down_revision = '52d54f94a30a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_qq'), 'users', ['qq'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_qq'), table_name='users')
    ### end Alembic commands ###
